### ISSUE TITLE
Chainloading u-boot on eval board at91sam9m10g45ek

### ISSUE THREAD

**Issue by fberndl** [linux4sam/u-boot-at91#13]
Hi,

is u-boot chainloading possible on at91sam9m10g45ek evaluation board?

**Comment by ehristev** [comment]
Hi,
What do you mean by chainloading ? Having u-boot load a second u-boot instead of linux kernel ?

**Comment by fberndl** [comment]
exactly

**Comment by ehristev** [comment]
Honestly: I do not know. I never tried.
You will be the first to report feedback about this.
My quick opinion: it should work.
Let me know if it does
