### ISSUE TITLE
sama5d27_wlsom1_ek board uboot missing bootargs

### ISSUE THREAD

**Issue by chenjiawei180** [linux4sam/u-boot-at91#20]
Hi, ALL
        I am use buildroot to build a sama5d27_wlsom1_ek image. But I found that doesn't work. That show miss VFS. So I find the U-boot without bootargs. So I add the bootargs and image is work.

**Comment by ehristev** [comment]
If you found a problem and solved, feel free to send a patch.

**Comment by chenjiawei180** [comment]
Hi ehristev,

I have never send a patch. So I need to learn how to send a patch to Github. thanks a lot.

**Comment by ehristev** [comment]
Okay, feel free to open a pull request with your patch, and we can have a look.
If you cannot do it, please describe your problem and solution in detail, and we will try to handle it.

**Comment by ehristev** [comment]
https://marc.info/?l=u-boot&m=162132859410790&w=1 
Patch for wlsom missing default bootargs is sent in mainline.
Thanks for reporting.
