### ISSUE TITLE
SAMA5D27 - UTMI issue?

### ISSUE THREAD

**Issue by TimJTi** [linux4sam/u-boot-at91#21]
I have a custom board using the SAMA5D27 and basically have (forked) u-boot-At91 running now. The only issue I have is that because it uses a 24MHz crystal (likethe SOM1 EV board) the UTMICKTRIM register needs to be set correctly (not just for USB - the CAN system runs best from the 480MHz UPLL clock).

I can see code (a U_BOOT_DRIVER I believe) that does this but I don't believe it is being called (an inspection of the relevant register from the final app (not Linux) that u-boot calls shows it has not been set, or not set correctly). And to be honest, I don't really know hoe uboot "calls" things anyway!

It could be a missing section in my custom dtsi or defconfig files but I can't see anything similar in EV board files, for example (only the SOM1 uses 24MHz crystal and the USB on that does work, for example...but howwhen is the upll code called to set the registers correctly!!??)

**Comment by ehristev** [comment]
Hi,
Normally in U-boot , drivers are probed on demand, so, if you do not access the USB, nothing will be called.

**Comment by TimJTi** [comment]
>From: Eugen Hristev ***@***.***> 
>Sent: 27 July 2021 08:38
>Hi,
>Normally in U-boot , drivers are probed on demand, so, 
>if you do not access the USB, nothing will be called.
—
Facepalm moment...doh! Many thanks Eugen...my USB-C is not yet working as it needs an FUSB302 driver (not looking forward to working out how to do that in u-boot!) so there's no VBUS detect connection on the board. That was probably an oversight and easily rectified actually - then I can get USB 2 functionality direct from U-Boot for firmware updating and no need, potentially, for FUSB302 support in u-boot.

I am checking the setting in the final app early init code (NuttX not Linux) and set the register if needs be, although NuttX generally assumes that board setup has already been done in most cases; so, it's not a defect as such but perhaps an enhancement would be to allow the UTMICKTRIM register to be correctly initialised regardless of USB connect/disconnect (how, should be easy?).

**Comment by ehristev** [comment]
Hi,

Do you still need assistance? If yes, could you point exactly where ?

**Comment by TimJTi** [comment]
I now understand that setting the UTMICKTRIM register only happens if you start USB (perhaps CAN - I haven't checked). I am setting it in the final app but I believe it is part of the basic clock setup that either AT91Bootstrap or u-boot-at91 should do.

Since there is no documentation to guide porting, or to the code, I have (for now) given up searching for randome code snippets that might do this in u-boot and am setting it from NuttX.

If you have any pointers to the "correct" place (and the relevant function calls) to initialise this register as part of the board code (or wherever) I would appreciate it :)

**Comment by cristibirsan** [comment]
Hi,

Each device manages the needed clocks and enabled them only if it is used. 

On U-Boot the configuration of UTMICKTRIM is done from this file ./drivers/clk/at91/clk-utmi.c. The clk_utmi_enable() is called when USB is started ( see: ehci_atmel_probe() -> ehci_atmel_enable_clk()). The link is done through the clocks described in device tree. Eg: 

usb2: ehci@00500000 {                                          
        compatible = "atmel,at91sam9g45-ehci", "usb-ehci";     
        reg = <0x00500000 0x100000>;                           
        clocks = <&utmi>, <&uhphs_clk>;                        
        clock-names = "usb_clk", "ehci_clk";                   
        status = "disabled";                                   
};

**Comment by TimJTi** [comment]
I think I'm "getting it" now - uboot has been a complete culture shock!!

There's perhaps a good argument that - since the clock isn't needed during normal ubooting - that it should be down to NuttX to enable it after all, and set the registers as needed.

I feel much better armed to tackle this now - many thanks.
