### ISSUE TITLE
key1/key2

### ISSUE THREAD

**Issue by TimJTi** [linux4sam/u-boot-at91#23]
Not an issue, just looking for some help. Tried the main Denx mailing list but zero response.

I would like to have alternate boots from user keys (derived from an I2C device if that's relevant) but if I set a key1 environment variable it is not executed in place of the environment-saved bootcmd script. The user guide says it should work like that (section 5.4.2 "User keys") but I have had zero success; I have searched every single file in the repo for "key1" and nothing helps (only reference is an env_set key1="on" - or "off" - for one board).

Anyone point me in the direction of better examples or documentation that shows how to use alternative boots based on startup key presses?

**Comment by ehristev** [comment]
Hi,

Unfortunately I never tried what you are doing. So, I cannot help, you have to search through the web and the sources... 
Maybe someone else reading this may have tried it.

**Comment by TimJTi** [comment]
Thanks for taking the time to reply - I have searched the sources here and on the main u-boot repo, and Google, but find no code snippets or discussion that helps.

May be it is broken; or changed and - like everything - not documented!!

**Comment by TimJTi** [comment]
Actually, it is Googling that may have misled me as I found a pdf "User Guide" that mentions key1 and key2. But the main Denx wiki makes no mention of it so I suspect it has been deprecated.

No matter; I am now simply rewriting the bootcmd environment variable depending on whether the keys are pressed or not and that works OK.
